### PR TITLE
Fix missing inner enum import on operations

### LINKED ISSUE #76: Missing enum import
My swagger.json was generated by swashbuckle (from an asp.net core web service). I trying to generate a kotlin client from this swagger.json, the generation run successfully. But on the api generated object enum import is missing.

I followed this [sample code](https://github.com/Yelp/swagger-gradle-codegen/tree/master/samples/generated-code). Maybe I missing somethings.

You can reproduce the bug from this repository : https://github.com/midoriiro/yelp-swagger-gradle-codegen-missing-enum-import

### PR DESCRIPTION
**Pull request by cortinico**
Previously inner types of complex types were not imported properly on
operations. This resulted in Retrofit interfaces missing some imports.

This commit introduces methods to inspect and import the inner types
used as result types of operations.

Fixes #76

Ping @macisamuele for the review

### CODE REVIEW

File: plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt [hunk 1]
```diff
@@ -142,10 +142,27 @@ class KotlinGenerator : SharedCodegen() {
     public override fun listTypeWrapper(listType: String, innerType: String) =
             "$listType<$innerType>"
 
+    public override fun listTypeUnwrapper(baseType: String) = baseType
+            .replace(" ", "")
+            .removeSuffix(">")
+            .removePrefix("List<")
+            .removePrefix("Array<")
```
Comment (macisamuele) [inline plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt]: As far as I can understand from the code the method will ever be called with `baseType` set to the type that will be output-ed on the file.
If the understanding is correct, then `Array<` should never be present

File: plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt [hunk 2]
```diff
@@ -142,10 +142,27 @@ class KotlinGenerator : SharedCodegen() {
     public override fun listTypeWrapper(listType: String, innerType: String) =
             "$listType<$innerType>"
 
+    public override fun listTypeUnwrapper(baseType: String) = baseType
+            .replace(" ", "")
+            .removeSuffix(">")
+            .removePrefix("List<")
```
Comment (macisamuele) [inline plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt]: I'd rather prefer using [`kotlinTypeMapping["list"]`](https://github.com/Yelp/swagger-gradle-codegen/blob/master/plugin/src/main/java/com/yelp/codegen/utils/KotlinLangUtils.kt#L121) so it might be moved into `SharedCodegen` as it will be _kotlin_ indpendent

File: plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt [hunk 3]
```diff
@@ -142,10 +142,27 @@ class KotlinGenerator : SharedCodegen() {
...
+            .removePrefix("Array<")
+
+    public override fun isListTypeWrapped(baseType: String) =
+            baseType.endsWith('>') && (baseType.startsWith("Array<") || baseType.startsWith("List<"))
```
Comment (macisamuele) [inline plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt]: As before: `Array` should not be possible and I would replace List with `kotlinTypeMapping["list"]`

File: plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt [hunk 4]
```diff
@@ -142,10 +142,27 @@ class KotlinGenerator : SharedCodegen() {
...
+
     @VisibleForTesting
     public override fun mapTypeWrapper(mapType: String, innerType: String) =
             "$mapType<${typeMapping["string"]}, $innerType>"
 
+    public override fun mapTypeUnwrapper(baseType: String) = baseType
+            .replace(" ", "")
+            .removeSuffix(">")
+            .removePrefix("Map<${typeMapping["string"]},")
```
Comment (macisamuele) [inline plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt]: ditto: `s/Map/typeMapping["map"]/`

File: plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt (hunk 1 above)
Comment (cortinico) [reply plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt]: Yup, you're right. Let's refactor this out :)

File: plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt (hunk 2 above)
Comment (cortinico) [reply plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt]: ++

**Comment by cortinico** [comment]
@macisamuele ready for another pass :) I've addressed all the comments.

> PS: personally I would have replaced isMapTypeWrapped with a regex matching of 
> the mapTypeWrapper (but not blocking)

You're more than welcome to add it once this gets merged :)
